### ISSUE TITLE
Catalog Match High-Fidelity + Additional Filter Functionality

### ISSUE THREAD

**Issue by michellelin1** [ctc-uci/aiss-frontend#41]
## Instructions
- By now, the core functionality of the Catalog should be mostly complete. Now that we also have the high-fidelity design, we can style the Catalog to match the provided design
- Since the Catalog is already decently styled, we’re also adding some additional functionality to this task under the request of the designers (who have now added some features that weren’t in the original version)
- We’d like to allow the user to select multiple filters in a single category (e.g. both Fall and Winter for season)
- We’d like to add a button to the Catalog allowing the user to unselect all of the filters, rather than having to manually unselect each filter

## Notes
- We highly recommend meeting with Vy to get an overview of the design for the Catalog!
- There is minor backend work that needs to be done allow for multiple filter selection in the `GET /catalog` route. Please make a new branch off of dev to work on these changes in the backend.

## Acceptance Criteria
- The design of the Catalog matches the high-fidelity design
- The user can select multiple filters in a single category, and the Catalog responds accordingly
- The user can click a button to remove all of the currently selected filters

## Resources
- [Catalog High Fidelity Design](https://www.figma.com/file/CmrgQbRKVLJWVhSzXxAdad/Low-High-Fidelity?type=design&node-id=761-4191&mode=design&t=8k4nXWspIhlHHe24-4)
- [Current Catalog Frontend](https://github.com/ctc-uci/aiss-frontend/blob/dev/src/pages/Catalog/Catalog.jsx)
- [Catalog Backend Routes](https://github.com/ctc-uci/aiss-backend/blob/dev/routes/catalog.js)

**Comment by seancfong** [comment]
@michellelin1 Does this issue require changing the edit functionality of an event?

![image](https://github.com/ctc-uci/aiss-frontend/assets/37647466/f34689d0-ead8-47ac-b967-a7da2949c662)

Looking at the design, an event can have multiple tags per attribute (seasons, years, categories, types), but the database schema needs to be updated since every event can have at most 1 per season/year/category/type. 

![image](https://github.com/ctc-uci/aiss-frontend/assets/37647466/f45eb33d-74b4-436b-be82-9b9ff1e2c89c)

**Comment by michellelin1** [comment]
@seancfong we have a task for next sprint to modify the backend table and post route to accommodate the multi-select so no need to worry about that
